[workspace]
members = [
    "node",
    "runtime/testnet",
    "pallets/university",
    "pallets/professor",
    "pallets/student",
    "pallets/lecture",
    "pallets/checked-validation",
    "traits",
    "types",
]
[profile.release]
panic = "unwind"
