[workspace]
members = [
    "node",
    "runtime",
    "pallets/university",
    "pallets/professor",
    "pallets/student",
    "pallets/checked-validation",
    "traits",
]
[profile.release]
panic = "unwind"
